version: '3'
services:
  web:
    image: tomcat:8.5
    ports:
      - "8081:8080"
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  apache:
    image: httpd:2.4
    ports:
      - "81:80"
    links:
      - web 
